title: "Banners"
description: |
  Banners are designed to provide a visual element that draws the attention of the user. They sometimes serve as a content divider.

patterns:
  about-me-banner:
    title: "About-me banner"
    description: |
      About-me banners are used on the homepage of the site to describe who I am and why I am a designer.
    fields:
      - name: heading1
        type: string
        example: "Hi!"
      - name: heading2
        type: string
        example: "You can call me G."
      - name: text
        type: string
        example: "I'm a graphic designer, visual artist, reformed policy wonk, and part-time quizmaster. I rock at creating brand identities."
      - name: button_text
        type: string
        example: "Find out more"
        required: true
      - name: button_url
        type: url
        example: "#more-about-me"
        required: true
